// Hand-authored - NOT regenerated by the FlutterFire CLI (unlike
// firebase_options.dart, which stays untouched). Selected only for
// AppFlavor.dev by app_bootstrap.dart; AppFlavor.prod keeps using the
// original, unmodified firebase_options.dart.
//
// Android: com.safetyalrt.alrt.dev is a real, separately-registered Firebase
// app within the same alrt-a6539 project as the prod app (see
// android/app/src/dev/google-services.json's own "com.safetyalrt.alrt.dev"
// client entry) - the appId below is copied verbatim from that committed
// file, not invented. apiKey/projectId/storageBucket are project-scoped, so
// they match firebase_options.dart's Android values exactly; only appId
// differs.
//
// iOS: no separate com.safetyalrt.alrt.dev app has been registered in the
// Firebase console yet - only one GoogleService-Info.plist exists in this
// repo, for the prod bundle id. The ios values below are therefore
// identical to firebase_options.dart's ios values, preserving today's
// existing dev-iOS behaviour unchanged (it already used the prod iOS
// identity before this file existed; it still does after). Once a real
// dev iOS app is registered in the Firebase console and its
// GoogleService-Info.plist downloaded, replace the ios block below with
// its real appId/apiKey - see V1_RECONCILIATION_REPORT.md §31.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsDev have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9QoyBvMjC3JuP6FG53LRkdtp7WzvFQk',
    appId: '1:705221000399:android:e626de52935e48e0858bba',
    messagingSenderId: '705221000399',
    projectId: 'alrt-a6539',
    storageBucket: 'alrt-a6539.firebasestorage.app',
  );

  // Same values as firebase_options.dart's `ios` block - see file header.
  // KNOWN GAP (see ios/TEST_IOS_SETUP.md §1): no iOS app for
  // com.safetyalrt.alrt.dev exists in Firebase project alrt-a6539 yet, so
  // this block still carries the PRODUCTION iOS app's values, inherited
  // unchanged from before the flavour split. Consequences on the iOS TEST
  // build until it is fixed: APNs push cannot work (the .dev bundle has no
  // APNs registration under this app id) and analytics/Crashlytics attribute
  // to the live app. Deliberately NOT replaced with invented values - Firebase
  // assigns apiKey/appId at registration. Paste the real "ALRT Dev" iOS values
  // here once registered; nothing else needs to change.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GtMYnTstiRxikCgUhZB_ENnyIAXzF54',
    appId: '1:705221000399:ios:42910fba9ef33a48858bba',
    messagingSenderId: '705221000399',
    projectId: 'alrt-a6539',
    storageBucket: 'alrt-a6539.firebasestorage.app',
    iosBundleId: 'com.safetyalrt.alrt',
  );
}
