#!/usr/bin/env python3
"""Turns the approved Claude Design boards (*.dc.html) into prototype screen templates.
Usage: python3 prototype/build_screens.py <boards dir>
Writes prototype/public/boards.js: window.BOARDS = { Main: "<html>", ... } and window.NAV (footer markup from Main).
Each board's footer <nav> is stripped (the shell draws one footer) and every href="X.dc.html" becomes data-nav="X"."""
import re, sys, json, os, glob
src = sys.argv[1]
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'public', 'boards.js')
PHONE = ['Splash', 'Onb1', 'Onb2', 'Onb3', 'Onb4', 'Onb5', 'Main', 'Places', 'Feed', 'Offline', 'Community', 'Detail', 'Ex1', 'Ex2', 'Ex3',
         'Report', 'Posted', 'Profile', 'Ready', 'Learn', 'Safety', 'FamilyEmpty', 'Family', 'Plan', 'Drill', 'Choose', 'Paywall', 'GroupPaywall']
boards = {}; nav = ''
for name in PHONE:
    s = open(os.path.join(src, name + '.dc.html')).read()
    body = s[s.index('</helmet>') + 9:s.index('</x-dc>')].strip()
    m = re.search(r'<nav .*?</nav>', body, re.S)
    if m and name == 'Main':
        nav = m.group(0)
    body = re.sub(r'\s*<nav .*?</nav>', '', body, flags=re.S)
    # root: let it grow with content, keep the designed minimum height
    body = re.sub(r'^(<div style="width: 390px; )height: (\d+)px;', lambda mm: f'{mm.group(1)}min-height: {mm.group(2)}px;', body)
    body = body.replace('overflow: hidden; background', 'overflow: visible; background', 1)
    # links become in-app navigation
    body = re.sub(r'href="([A-Za-z0-9]+)\.dc\.html"', r'href="#" data-nav="\1"', body)
    # inner scroll regions were clipped on the static board; let them grow
    body = body.replace('style="flex: 1; overflow: hidden;', 'style="flex: 1;')
    body = body.replace('style="flex: 1; padding:', 'style="flex: 1; padding:')
    boards[name] = body
nav = re.sub(r'href="([A-Za-z0-9]+)\.dc\.html"', r'href="#" data-nav="\1"', nav)
# widget tiles from the Widgets board (the "Improved" set)
ws = open(os.path.join(src, 'Widgets.dc.html')).read(); wb = ws[ws.index('</helmet>') + 9:ws.index('</x-dc>')]
i0 = wb.index('Improved'); tiles = []
for mm in re.finditer(r'<div style="width: (338|158)px; height: 158px; border-radius: 24px;[^"]*"', wb[i0:]):
    start = i0 + mm.start(); depth = 0; j = start
    while True:
        o = wb.find('<div', j); c = wb.find('</div>', j)
        if c == -1: break
        if o != -1 and o < c: depth += 1; j = o + 4
        else:
            depth -= 1; j = c + 6
            if depth == 0: break
    tiles.append(wb[start:j])
with open(out, 'w') as f:
    f.write('// Generated by build_screens.py from the Claude Design canvas. Do not edit by hand.\n')
    f.write('window.BOARDS = ' + json.dumps(boards) + ';\n')
    f.write('window.NAV = ' + json.dumps(nav) + ';\n')
    f.write('window.WIDGET_TILES = ' + json.dumps(tiles) + ';\n')
print('wrote', out, len(boards), 'boards', sum(len(v) for v in boards.values()), 'bytes')
