#!/usr/bin/env python3
"""Captures every screen of the running prototype and writes prototype/screens/map.json + map.html
(screen name, board it comes from, screenshot, and the links out of it, read from the live DOM)."""
import json, os, re, base64
from playwright.sync_api import sync_playwright
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, 'screens', 'map'); os.makedirs(OUT, exist_ok=True)
URL = 'http://localhost:4173'
ACT_LABEL = {'open': 'Alert detail', 'ask': 'Ask ALRT sheet', 'openfilters': 'Filters sheet', 'mapkey': 'Map key sheet', 'opennotes': 'notes', 'paywall': 'Paywall', 'sheet': 'sheet', 'cisheet': 'Check in sheet', 'askcisheet': 'Ask for a check-in sheet', 'sosopen': 'SOS sheet', 'goinvite': 'invite', 'loadprofile': 'circleprofile', 'loadsoslists': 'soslists', 'loadplaces': 'famplaces', 'loadhist': 'soshistory', 'membersheet': 'Member sheet', 'loadmine': 'myalrts', 'loadpoints': 'points', 'loadmanage': 'manage', 'loadnotes': 'managenotes', 'loadblocked': 'blocked', 'loadlb': 'leaderboard', 'logoutsheet': 'Log out sheet', 'emailsheet': 'Email sign-in sheet', 'flagsheet': 'Report alert sheet', 'sharesheet': 'Share sheet', 'rollcall': 'rollcall', 'viewsos': 'sosreceiver', 'viewjourney': 'sharedjourney', 'sosedit': 'soslistedit', 'guideopen': 'guide', 'leavesheet': 'Leave sheet', 'transfer': 'Hand over sheet', 'onbgo': 'Main', 'closepay': 'back', 'refusalgo': 'Paywall / fix', 'forgotopen': 'forgot', 'dupforce': 'Posted', 'post': 'Posted', 'buy': 'store then Main', 'buygrp': 'store then Family', 'register': 'onbdone', 'login': 'Main', 'oauth': 'onbdone', 'onbagreego': 'Onb3', 'onbprime': 'Onb4', 'recover': 'Main', 'delacct': 'deleted', 'signout': 'Splash'}
def links_of(pg):
    return pg.evaluate("""()=>{const out=new Set();for(const a of document.querySelectorAll('#screen [data-nav], #screen [data-act], #navwrap [data-nav]')){const t=(a.innerText||a.getAttribute('aria-label')||'').trim().split('\\n')[0].slice(0,40);if(a.dataset.nav)out.add(JSON.stringify({to:a.dataset.nav,via:t}));else if(a.dataset.act&&!['close','noop','toast','filt','filtreset','repcat','repobs','repsev','lvl','onbwho','onbagree','cohort','planpick','grptier','jmin','jrecip','jlivetoggle','sosloc','sosprec','soslist','asksel','slsel','sldef','setcolor','pushf','pushcat','accvib','accra','suptype','flagr','follow','readaloud','vote','gtoggle','unlock','routemode','routego','retry','primeon','primelater','unsub','addplace','fpadd','fpdel','fpprefs','schedadd','scheddel','savenick','gsave','mkinvite','revoke','slsave','sldel','sosextend','sosstop','sosresp','jext','jstop','checkon','locreq','locresp','ci','askgo2','rccancel','removem','transferto','closecircle','leave','takeover','pickcircle','join','join2','mkcircle','mkcircle2','setlevel','setsharing','setlang','testpush','childtoggle','unblock','supsend','widgetadd','restore','bind','upgradego','askgo','dupconfirm','cihazard','sharefam','flag','block','selffund','guidedone','plansave','drillstart','cohortclear','authmode','forgot','locpick','onbagree'].includes(a.dataset.act))out.add(JSON.stringify({to:a.dataset.act,via:t}));}return [...out].map(JSON.parse)}""")
entries = []
with sync_playwright() as p:
    b = p.chromium.launch(executable_path='/opt/pw-browsers/chromium', args=['--no-sandbox']); pg = b.new_page(viewport={'width': 760, 'height': 900})
    pg.goto(URL); pg.wait_for_timeout(1500)
    box = pg.locator('#phone').bounding_box(); clip = {'x': box['x'], 'y': box['y'], 'width': box['width'], 'height': box['height']}
    def shot(name, board, note=''):
        pg.wait_for_timeout(350); f = os.path.join(OUT, name + '.png'); pg.screenshot(path=f, clip=clip)
        ls = links_of(pg); ls = [{'to': ACT_LABEL.get(l['to'], l['to']), 'via': l['via']} for l in ls]
        entries.append({'screen': name, 'board': board, 'note': note, 'file': 'map/' + name + '.png', 'links': ls}); print(name, len(ls))
    def click(t): pg.click(f'[data-testid="{t}"]')
    def tab(t): click('tab-' + t); pg.wait_for_timeout(600)
    def setstate(js): pg.evaluate(js + '; draw()'); pg.wait_for_timeout(400)
    shot('Splash', 'Splash'); click('onb-next'); shot('Onb1', 'Onb1'); click('onb-next'); shot('Onb2', 'Onb2')
    for i in range(3): pg.click(f'[data-act=onbagree][data-i="{i}"]')
    click('age'); click('onb-next'); shot('Onb3', 'Onb3'); pg.click('[data-id=all]'); click('onb-later'); shot('Onb4', 'Onb4'); click('onb-next'); shot('Onb5', 'Onb5')
    click('email-open'); shot('Onb5-email', 'sheet', 'Email sign-in sheet'); pg.fill('[data-testid=email]', 'sarah@example.com'); pg.fill('[data-testid=password]', 'pw'); click('register'); pg.wait_for_timeout(1600); shot('SetUpComplete', 'new', 'Endowed progress: first 20 points')
    click('onbgo'); shot('Priming', 'sheet', 'Notification ask at the moment of wanting'); click('prime-on'); pg.wait_for_timeout(400)
    shot('Main', 'Main'); click('filters-btn'); shot('Filters', 'sheet'); click('filt-done'); click('ask-btn'); pg.wait_for_timeout(300); shot('AskALRT', 'sheet'); pg.evaluate("A.close(); draw()")
    pg.evaluate("A.mapkey(); draw()"); pg.wait_for_timeout(300); shot('MapKey', 'sheet'); pg.evaluate("A.close(); draw()")
    click('places-btn'); pg.wait_for_timeout(400); shot('Places', 'Places'); pg.fill('[data-testid=place-name]', 'Home'); click('add-place'); pg.wait_for_timeout(400); pg.fill('[data-testid=place-name]', 'Work'); click('add-place'); pg.wait_for_timeout(500); shot('Refusal-SavedPlace', 'sheet', 'AccessRefusalSheet SAVED_PLACE_LIMIT'); click('refusal-cta'); pg.wait_for_timeout(400); shot('Paywall', 'Paywall'); pg.click('[data-testid=back]'); pg.wait_for_timeout(300); shot('Choose', 'Choose'); click('pick-grp'); pg.wait_for_timeout(300); shot('GroupPaywall', 'GroupPaywall'); pg.click('[data-testid=back]'); pg.click('[data-testid=continue-free]'); pg.wait_for_timeout(300)
    setstate("st.tab='route'"); shot('Route', 'new', 'Check a route (navigation, free)')
    tab('feed'); shot('Feed', 'Feed'); pg.click('[data-testid=alert-aws] >> nth=0'); pg.wait_for_timeout(400); shot('Detail', 'Detail'); click('share'); shot('ShareLink', 'sheet'); pg.evaluate("A.close(); draw()"); click('back')
    pg.evaluate("st.detail = st.hazards.find(h=>h.board==='Ex1').id; st.tab='Ex1'; draw()"); pg.wait_for_timeout(300); shot('Ex1', 'Ex1'); pg.evaluate("st.detail = st.hazards.find(h=>h.board==='Ex2').id; st.tab='Ex2'; draw()"); pg.wait_for_timeout(300); shot('Ex2', 'Ex2'); pg.evaluate("st.detail = st.hazards.find(h=>h.board==='Ex3').id; st.tab='Ex3'; draw()"); pg.wait_for_timeout(300); shot('Ex3', 'Ex3')
    pg.evaluate("st.detail = st.hazards.find(h=>h.source==='community').id; st.tab='Community'; draw()"); pg.wait_for_timeout(300); shot('Community', 'Community'); click('overflow'); shot('ReportAlert', 'sheet', 'Flag or block'); pg.evaluate("A.close(); draw()")
    pg.evaluate("st.offline=true; draw()"); pg.wait_for_timeout(300); pg.evaluate("st.tab='Offline'; draw()"); pg.wait_for_timeout(300); shot('Offline', 'Offline'); pg.evaluate("st.offline=false; st.tab='notes'; draw()"); pg.wait_for_timeout(300); shot('Notifications', 'new', 'Push inbox')
    tab('report'); shot('Report', 'Report'); click('cat-traffic'); pg.click('[data-act=repobs] >> nth=0'); click('post'); pg.wait_for_timeout(800); shot('Posted', 'Posted'); click('done')
    pg.evaluate("st.tab='selectloc'; draw()"); pg.wait_for_timeout(300); shot('SelectLocation', 'new')
    tab('ready'); shot('Ready', 'Ready'); click('make-plan'); pg.wait_for_timeout(300); shot('Plan', 'Plan'); click('plan-save'); pg.wait_for_timeout(300); click('drill-open'); pg.wait_for_timeout(300); shot('Drill', 'Drill'); tab('ready'); click('learn-open'); pg.wait_for_timeout(300); shot('Learn', 'Learn'); click('guide-open'); pg.wait_for_timeout(300); shot('Guide', 'new', 'Guide detail'); tab('ready'); pg.evaluate("st.tab='Safety'; draw()"); pg.wait_for_timeout(300); shot('Safety', 'Safety')
    tab('family'); shot('FamilyEmpty', 'FamilyEmpty'); click('make-circle-open'); shot('CreateGroup', 'sheet'); click('make-circle'); pg.wait_for_timeout(1500); pg.click('[data-dev=friend]'); pg.wait_for_timeout(2500); shot('Family', 'Family')
    click('checkin'); shot('CheckIn', 'sheet', 'Consent sheet'); click('ci-none'); pg.wait_for_timeout(600); shot('Refusal-IndividualRequired', 'sheet', 'AccessRefusalSheet INDIVIDUAL_REQUIRED (free user in an uncovered group)'); pg.evaluate("A.close(); draw()")
    pg.evaluate("""async()=>{const t=localStorage.getItem('alrt_tok');const me=await (await fetch('/api/user/profile',{headers:{authorization:'Bearer '+t}})).json();await fetch('/api/revenuecat/webhook',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:{type:'INITIAL_PURCHASE',app_user_id:me.id,product_id:'alrt_individual_monthly',is_trial_period:true}})})}"""); pg.wait_for_timeout(300); tab('family'); click('checkin'); pg.wait_for_timeout(300); click('ci-none'); pg.wait_for_timeout(800); click('askall'); shot('AskCheckIn', 'sheet'); pg.evaluate("A.close(); draw()"); click('checkon'); pg.wait_for_timeout(1200); pg.click('[data-testid=waiting-row]'); pg.wait_for_timeout(400); shot('RollCall', 'new'); click('rc-cancel'); pg.wait_for_timeout(500)
    click('sos-open'); pg.wait_for_timeout(500); shot('SOS', 'sheet', 'Hold 3 seconds'); pg.evaluate("A.close(); draw()"); pg.click('[data-dev=friendsos]'); pg.wait_for_timeout(1400); pg.click('[data-testid=sos-strip]'); pg.wait_for_timeout(500); shot('SOSReceiver', 'new'); click('sos-seen'); pg.wait_for_timeout(300)
    ft = pg.evaluate("async()=>(await (await fetch('/api/__friend-token')).json()).token"); sid = pg.evaluate("st.viewSos.id"); pg.evaluate("async([t,id])=>{await fetch('/api/family/sos/'+id+'/resolve',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+t},body:'{}'})}", [ft, sid]); pg.wait_for_timeout(1800); pg.evaluate("A.viewsos({dataset:{id:st.viewSos.id}}).then(()=>draw())"); pg.wait_for_timeout(500); shot('SOSEnded', 'new')
    tab('family'); click('hist-open'); pg.wait_for_timeout(300); shot('PastSOS', 'new'); tab('family'); click('journey-open'); pg.wait_for_timeout(300); shot('Journey', 'new'); click('jm-60'); click('jstart'); pg.wait_for_timeout(800); shot('JourneyActive', 'new'); click('jstop'); pg.wait_for_timeout(300)
    pg.click('[data-dev=friendjourney]'); pg.wait_for_timeout(1400); tab('family'); pg.click('[data-testid=shared-journey]'); pg.wait_for_timeout(400); shot('SharedJourney', 'new')
    pg.click('[data-dev=friendask]'); pg.wait_for_timeout(1400); tab('family'); pg.click('[data-testid=loc-strip]'); pg.wait_for_timeout(300); shot('LocationRequest', 'sheet'); click('loc-decline'); pg.wait_for_timeout(400)
    rows = pg.query_selector_all('[data-testid=member-row]'); [r for r in rows if 'Alex' in r.inner_text()][0].click(); pg.wait_for_timeout(300); shot('MemberSheet', 'sheet'); pg.evaluate("A.close(); draw()")
    click('member-me'); pg.wait_for_timeout(400); shot('CircleProfile', 'new'); click('sharing-open'); pg.wait_for_timeout(300); shot('SharingLevel', 'new'); click('back'); pg.wait_for_timeout(300); click('soslists-open'); pg.wait_for_timeout(400); shot('SOSLists', 'new'); click('sl-new'); pg.wait_for_timeout(300); shot('SOSListEdit', 'new'); click('back'); click('back'); pg.wait_for_timeout(300)
    click('invite-open'); pg.wait_for_timeout(400); click('mk-invite'); pg.wait_for_timeout(400); shot('Invite', 'new'); click('back'); pg.wait_for_timeout(300); click('gsettings'); pg.wait_for_timeout(300); shot('GroupSettings', 'new'); click('leave'); shot('LeaveSheet', 'sheet'); pg.evaluate("A.close(); draw()"); click('back'); pg.wait_for_timeout(300)
    click('places-open'); pg.wait_for_timeout(300); shot('FamilyPlaces', 'new'); click('back'); pg.wait_for_timeout(300); click('plan-open'); pg.wait_for_timeout(300); shot('PlanAndCover', 'new'); click('back'); pg.wait_for_timeout(300)
    pg.evaluate("async()=>{await fetch('/api/family/circles',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+localStorage.getItem('alrt_tok')},body:JSON.stringify({name:'Work'})})}"); pg.wait_for_timeout(300); tab('family'); click('switch'); pg.wait_for_timeout(300); shot('SwitchCircle', 'new'); pg.click('[data-testid=circle-pick] >> nth=0'); pg.wait_for_timeout(300)
    pg.evaluate("circ().hostTransition={hostName:'Sarah',daysLeft:7}; draw()"); pg.wait_for_timeout(300); shot('GroupPaused', 'new', 'Host hand-over'); pg.evaluate("circ().hostTransition=null")
    tab('me'); shot('Profile', 'Profile'); click('notes-open'); pg.wait_for_timeout(300); shot('ManageNotifications', 'new'); click('back'); click('points-open'); pg.wait_for_timeout(300); shot('Points', 'new'); click('lb-open'); pg.wait_for_timeout(300); shot('Leaderboard', 'new'); click('back'); click('back')
    click('manage-open'); pg.wait_for_timeout(300); shot('MyPlans', 'new'); click('back'); click('mine-open'); pg.wait_for_timeout(300); shot('MyALRTs', 'new'); click('back'); click('child-open'); pg.wait_for_timeout(300); shot('ChildMode', 'new'); click('back'); click('blocked-open'); pg.wait_for_timeout(300); shot('BlockedAccounts', 'new'); click('back'); click('support-open'); pg.wait_for_timeout(300); shot('Support', 'new'); click('back')
    pg.evaluate("st.tab='accessible'; draw()"); pg.wait_for_timeout(300); shot('AccessibleAlerts', 'new'); tab('me'); click('widgets-open'); pg.wait_for_timeout(300); shot('AddWidget', 'sheet'); pg.evaluate("A.close(); draw()"); click('share-open'); pg.wait_for_timeout(300); shot('ShareALRT', 'sheet'); pg.evaluate("A.close(); draw()"); click('language-open'); pg.wait_for_timeout(300); shot('Language', 'sheet'); pg.evaluate("A.close(); draw()"); click('legal-open'); pg.wait_for_timeout(300); shot('Legal', 'sheet'); pg.evaluate("A.close(); draw()")
    click('delete-open'); pg.wait_for_timeout(300); shot('DeleteAccount', 'new'); click('del-confirm'); pg.wait_for_timeout(800); shot('AccountDeleted', 'new'); click('recover'); pg.wait_for_timeout(600)
    pg.click('[data-dev=push]'); pg.wait_for_timeout(300); shot('LockScreenPush', 'new'); pg.click('[data-testid=lock]'); pg.click('[data-dev=forceupdate]'); pg.wait_for_timeout(300); shot('ForceUpdate', 'new'); pg.click('[data-dev=forceupdate]'); pg.wait_for_timeout(300)
    pg.click('[data-dev=igfooter]'); pg.wait_for_timeout(300); tab('alerts'); shot('Main-InstagramFooter', 'alt', 'Dev toggle: icon-only footer'); pg.click('[data-dev=igfooter]')
    tab('me'); click('signout'); pg.wait_for_timeout(300); shot('LogOut', 'sheet'); click('logout-go'); pg.wait_for_timeout(500); click('have-account'); pg.wait_for_timeout(300); click('email-open'); click('login-mode'); click('forgot-link'); pg.wait_for_timeout(300); shot('ForgotPassword', 'new')
    b.close()
json.dump(entries, open(os.path.join(HERE, 'screens', 'map.json'), 'w'), indent=1)
print(len(entries), 'screens')
